# Generated by Django 4.2.3 on 2023-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='new_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
